### ISSUE TITLE
Can I break-off the top/bottom row and use it as single switch pcb?

### ISSUE THREAD

**Issue by buitrung** [Bastardkb/dactyl-pcb-single-col#1]
Thanks for your PCB design.
I'm using it to build my first dactyl. I'm confused whether I could break off the top/bottom row and use it for each switch in the thumb cluster, something like the Amoeba single switch PCB?

If it is possible, how can I solder the wires to connect them altogether?
I'm figuring out that I need to solder the column wire with 1 end of Kailh hotswap and the row wires with 1 end of diode and the other end of Kailh hotswap, is it correct?

Thanks for your help!

**Comment by bstiq** [comment]
Hi !

You can do it like you mentioned yes.
I recommend going with amoebas though, as it'll be way easier for wiring.

**Comment by buitrung** [comment]
I've figured out, there're only 2 wires to be solder on each single pcb, 1 wire soldered to cathode (of diode), 1 wire soldered to the end of Kailh hotswap on the other side
